### PR TITLE
Devcontainer added

### PR DESCRIPTION
**Pull request by nelson-lojo**
Created `devcontainer.json` to help standardize development environments. This allows contributors to work in the same environment at all times without relying on or changing local package installs -- instead they only need a working docker+vscode install. Additionally, a devcontainer spec allows users to spin up github codespaces with various IDEs (we'll only support vscode development in this repo) and thus remove the need for *any* local installation.

Dev containers do come with a drawback -- all environment changes need to be checked in to git to allow devs to actually use the codebase. 

Note: codependent with #13 in that the pyright/pylance extension install+settings in vscode should be set from within `devcontainer.json`

### CODE REVIEW

**Comment by nelson-lojo** [comment]
Should we consider adding [cuda support](https://github.com/devcontainers/features/tree/main/src/nvidia-cuda)? The use case would be for developing with a GPU on a local machine with docker+vscode installed

@riensou what do you think

**Comment by KesavaViswanadha** [comment]
Not sure if this is the right place to put it, but update the transformers library version from 4.17.0 to the latest version (4.39.3) because of increased architecture support

**Comment by KesavaViswanadha** [comment]
Getting this error when trying to create a new codespace off of the dev container: 

Screenshot 2024-04-16 at 4 30 20 PM

Currently I can only get the codespace to run in recovery mode. 

image

**Comment by nelson-lojo** [comment]
@KesavaViswanadha Can you share a paste of the creation log? It worked first time for me.

**Comment by KesavaViswanadha** [comment]
Reran, for some reason it works now.... okay

**Review by riensou — APPROVED** [review]
was able to create a codespace, everything works for me

**Comment by riensou** [comment]
thought I needed to install docker @nelson-lojo

**Pull request merged**
